import Head from 'next/head'
import { useState } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [address, changeAddress] = useState('')
  const [balance, changeBalance] = useState(0)
  async function connectwallet() {
    const accounts = await ethereum.request({ method: 'eth_requestAccounts' })
    const account = accounts[0]
    console.log(account)
    changeAddress(account)
  }

  async function getBalance() {
    if(address === ''){
      alert('Connect your wallet')
    }else{
      const accountBalance = await ethereum.request({method: 'eth_getBalance', params: [address, 'latest']})
      changeBalance(parseInt(accountBalance))
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Metamask Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Metamask Demo
        </h1>
        <h2>
          Connected address: {address}
        </h2>
        <h3>
          Your Account Balance: {balance}
        </h3>
        <div className={styles.grid}>
          <button className={styles.card} onClick={connectwallet}>
            <p>Connect Wallet</p>
          </button>

          <button className={styles.card} onClick={getBalance}>
            <p>Get Balance</p>
          </button>
        </div>
      </main>
    </div>
  )
}
